name: Update GitHub Activity

on:
  schedule:
    - cron: "0 */6 * * *"   # refreshes every 6 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jamesgeorge007/github-activity-readme@master
        with:
          MAX_LINES: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
